
export const errorHandling = (req,res,next) => {
    try {
    console.error(error)
} catch (error) {
    console.error(error)
}
}

